import OpenAI from 'openai';
import Settings from '../models/Settings.js';

/**
 * Centralized AI Response Generator
 * @param {string} userId - ID of the user owning the bot
 * @param {string} userMessage - The text received from the customer
 * @returns {Promise<string>} - The AI generated response text
 */
export const generateAIResponse = async (userId, userMessage, workspaceId = null) => {
  const dotenvModule = await import('dotenv');
  dotenvModule.default.config();

  const settingsQuery = { userId };
  if (workspaceId) {
    settingsQuery.workspaceId = workspaceId;
  }

  try {
    const userSettings = await Settings.findOne(settingsQuery);
    
    const groqKey = process.env.GROQ_API_KEY;
    const openaiKey = process.env.OPENAI_API_KEY;
    const geminiKey = process.env.GEMINI_API_KEY;

    console.log(`🔍 AI DEBUG: Groq:${!!groqKey}, OpenAI:${!!openaiKey}, Gemini:${!!geminiKey}`);

    if (!groqKey && !openaiKey) {
      console.warn("⚠️ No AI API Keys configured in env.");
      return userSettings?.aiFallbackMessage || "I'm currently in limited mode, please contact support.";
    }

    const aiName = userSettings?.aiName || "Zen Assistant";
    const aiTone = userSettings?.aiTone || "friendly and concise";
    const aiKnowledgeBase = userSettings?.aiKnowledgeBase || "You are an AI helpful assistant.";
    const aiTemperature = userSettings?.aiTemperature !== undefined ? userSettings.aiTemperature : 0.7;


    const callOpenAI = async (client, modelName) => {
      const response = await client.chat.completions.create({
        model: modelName,
        messages: [
          { role: "system", content: `You are ${aiName}. Tone: ${aiTone}.\nSTRICT INSTRUCTION: You must answer based ONLY on the following knowledge base: ${aiKnowledgeBase}.\nDo NOT hallucinate or answer questions outside this knowledge base. If the user asks something unrelated, reply politely that you can only assist with business-related inquiries. Keep replies very short and human-like.` },
          { role: "user", content: userMessage }
        ],
        temperature: aiTemperature,
        max_tokens: 350,
      });
      return response.choices[0]?.message?.content;
    };

    const callGemini = async () => {
      const axios = (await import('axios')).default;
      try {
        const url = `https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=${geminiKey}`;
        const response = await axios.post(url, {
          contents: [{
              parts: [{ text: `System Instructions: You are ${aiName}. Tone: ${aiTone}.\nSTRICT INSTRUCTION: You must answer based ONLY on the following knowledge base: ${aiKnowledgeBase}.\nDo NOT hallucinate or answer questions outside this knowledge base. If the user asks something unrelated, reply politely that you can only assist with business-related inquiries. Keep replies very short and human-like.\nUser: ${userMessage}` }]
          }],
          generationConfig: { temperature: Number(aiTemperature) || 0.7, maxOutputTokens: 350 }
        });
        
        const extractedText = response.data?.candidates?.[0]?.content?.parts?.[0]?.text;
        if (extractedText) return extractedText;
        throw new Error("No response generated by Gemini");
      } catch (err) {
        const errorMsg = err.response?.data ? JSON.stringify(err.response.data) : err.message;
        throw new Error(`GEMINI_ERROR: ${errorMsg}`);
      }
    };

    let reply = null;

    if (geminiKey) {
      console.log(`🚀 Trying Gemini for user ${userId}...`);
      try {
        reply = await callGemini();
        if (reply) {
          console.log(`✅ Success with Gemini!`);
          return reply;
        }
      } catch (err) {
        console.error("Gemini Primary Failed:", err.message);
      }
    }

    if (groqKey) {
      const groqModels = ['llama-3.3-70b-versatile', 'llama-3.1-70b-versatile', 'llama-3.1-8b-instant'];
      const cleanGroqKey = groqKey.trim();
      
      for (const groqModel of groqModels) {
        console.log(`🚀 Trying Groq (${groqModel}) as backup...`);
        try {
          const groq = new OpenAI({ apiKey: cleanGroqKey, baseURL: "https://api.groq.com/openai/v1" });
          reply = await callOpenAI(groq, groqModel);
          if (reply) {
            console.log(`✅ Success with Groq fallback: ${groqModel}`);
            return reply;
          }
        } catch (err) {
          console.error(`Groq (${groqModel}) Failed:`, err.message);
          if (err.status === 401) break;
        }
      }
    }

    console.error("❌ AI API Error: All active services failed.");
    return userSettings?.aiFallbackMessage || "I'm currently in limited mode, please contact support.";

  } catch (err) {
    console.error("❌ AI API Error:", err.message);
    
    const finalSettings = await Settings.findOne(settingsQuery);
    return finalSettings?.aiFallbackMessage || "I'm currently busy, please try again in a bit! 😊";
  }
};
